/*
1.	Ustvarite PB DemoPB. Oglejte si, kako je mySQL implementiral PB (Windows Explorer). Kaj je PB
2.	Ustvarite tabelo Predmet (PID:N, Kratica:A3, ImePredmeta:A20, kreditneTocke:N, Opis:A200)
3.	Podatek PID naj bo tipa auto increment in naj se začne s številko 100. Nabor znakov tabele naj bo utf-8. mySQL način hranjenja tabele naj bo privzet.
4.	Oglejte si strukturo tabele Predmet. Kateri način hranjenja (engine) je uporabljen?
5.	V tabelo Predmet vpišite 5 zapisov (matematika, podatkovne baze, fizika, spletne aplikacije, multimedijska tehnologija). Vrednosti ostalih atributov so poljubne.
6.	Tabeli dodajte atribut stUrNaTeden. Veljavne vrednosti so 2, 3, 4, 5, ali 6.
7.	Oglejte si strukturo tabele predmet.
8.	Posodobite podatek stUrNaTeden (matematika 4, podatkovne baze 4, fizika 3, spletne aplikacije 5, multimedijska tehnologija 4).
9.	Tabeli dodajte atribut opomba. Vrednost atributa je poljubna kombinacija besed: zahtevno, zanimivo, uporabno, praktično.
10.	Izpišite vsebino tabele Predmet.
11.	Posodobite podatke tako, da bo matematika zahtevna in uporabna, podatkovne baze pa zanimive in uporabne. Fizika naj bo samo zanimiva.
12.	Izpišite imena predmetov, ki imajo 2 opombi.
13.	Izpišite imena predmetov, ki nimajo opombe uporabno.
14.	Izpišite imena predmetov, ki se izvajajo 4 ure tedensko.
15.	Uporaba orodja mysqldump (ne PHPmyadmin!).PB DemoPB izvozite v skripto DemoPB.sql. S programom Notepad++ si oglejte vsebino skripte.
*/

-- You get what you f*** deserve.
-- Generated by GitHub Copilot (with me pressing tab like a monkey, yes for wrong stuff too)

CREATE DATABASE DemoPB;

CREATE TABLE Predmet (
    PID INT AUTO_INCREMENT,
    Kratica VARCHAR(3) NOT NULL,
    ImePredmeta VARCHAR(20) NOT NULL,
    KreditneTocke INT,
    Opis VARCHAR(200),
    PRIMARY KEY (PID)
) CHARACTER SET utf8;

INSERT INTO Predmet (Kratica, ImePredmeta, KreditneTocke, Opis) VALUES
    ('MAT', 'Matematika', 5, 'Predmet za matematike'),
    ('PBA', 'Podatkovne baze', 4, 'Predmet za podatkovne baze'),
    ('FIZ', 'Fizika', 3, 'Predmet za fiziko'),
    ('SPL', 'Spletne aplikacije', 5, 'Predmet za spletne aplikacije'),
    ('MUL', 'Multimedijska tehnologija', 4, 'Predmet za multimedijsko tehnologijo');

ALTER TABLE Predmet ADD StUrNaTeden INT;
ALTER TABLE Predmet ADD CONSTRAINT StUrNaTeden_check CHECK (StUrNaTeden IN (2, 3, 4, 5, 6));

UPDATE Predmet SET StUrNaTeden = 4 WHERE Kratica = 'MAT';
UPDATE Predmet SET StUrNaTeden = 4 WHERE Kratica = 'PBA';
UPDATE Predmet SET StUrNaTeden = 3 WHERE Kratica = 'FIZ';
UPDATE Predmet SET StUrNaTeden = 5 WHERE Kratica = 'SPL';
UPDATE Predmet SET StUrNaTeden = 4 WHERE Kratica = 'MUL';

ALTER TABLE Predmet ADD Opomba VARCHAR(200);
ALTER TABLE Predmet ADD CONSTRAINT Opomba_check CHECK (Opomba IN ('zahtevno', 'zanimivo', 'uporabno', 'prakticno'));

UPDATE Predmet SET Opomba = 'zahtevno' WHERE Kratica = 'MAT';
UPDATE Predmet SET Opomba = 'zanimivo' WHERE Kratica = 'PBA';
UPDATE Predmet SET Opomba = 'uporabno' WHERE Kratica = 'FIZ';
UPDATE Predmet SET Opomba = 'prakticno' WHERE Kratica = 'SPL';
UPDATE Predmet SET Opomba = 'zanimivo' WHERE Kratica = 'MUL';

DELETE FROM Predmet;

UPDATE Predmet SET Opomba = 'zahtevno' WHERE Kratica = 'MAT';
UPDATE Predmet SET Opomba = 'zanimivo' WHERE Kratica = 'PBA';
UPDATE Predmet SET Opomba = 'uporabno' WHERE Kratica = 'FIZ';
UPDATE Predmet SET Opomba = 'prakticno' WHERE Kratica = 'SPL';
UPDATE Predmet SET Opomba = 'zanimivo' WHERE Kratica = 'MUL';

SELECT ImePredmeta FROM Predmet WHERE StUrNaTeden = 4;

-- 15
-- mysqldump -u root -p DemoPB > DemoPB.sql

/*
1.	Kreirajte PB GlasbenaZbirka_innoDB. Nabor znakov in razvrščanje naj bo prilagojenom ‘našim’ uporabnikom. 
2.	Kreirajte naslednje tabele in pri tem povsod uporabite engine innoDB:
	Avtor(AvtorID:N, Ime:A20, Priimek:A20, Opus) 
	Posnetek (PID:N, Naslov:A30, Genre:A20, Trajanje:D, AvtorID:N->Avtor)
	CD(CDID:N, NaslovCD:A30, Cena:N,Opombeo:A150, lastnik:N)
	Vsebina(CDID:N->CD,PID:N->Posnetek)
	Lastnik(LID:N, Ime:A20, Priimek:A20, Tel:A20, eMail:A30)
	Atribut Opus naj bo večvrednostni atribut, ki ga boste realizirali z množico, dovoljene vrednosti so: opera, kantata, simfonija, koncert, balada, drugo.
	Za podatek Trajanje uporabite tip Time.
	Podatek Genre naj bo naštevnega tipa (enum), zaloga vrednosti je klasika, pop, jazz.
	Za podatek Cena uporabite tip decimal in določite natako 2 decimalni mesti.
	Ali je postavljanje integritetnih omejitev tujih ključev (v tabeli Posnetek Vsebina) uspelo  - preveri s show create table? Zakaj?

3.	Izpišite seznam table in natančen opis vseh tabel. // show create table 
4.	Atribut lastnik tabele CD spremenite tako, da bo tuji ključ, ki kaže na tabelo Lastnik.
5.	Tabeli CD dodajte atribut Leto tipa year.
6.	Izpišite opis tabele CD.
7.	Ustvarite tabelo Owner, ki bo imela enako strukturo kot tabela Lastnik.
8.	V tabelah Avtor in Lastnik zamenjajte vrstni red atributov ime in priimek.
9.	V tabelo Avtor dodajte naslednje zapise (stavek INSERT INTO):
10, Orff, Carl, opera, kantata, drugo
20, Gounod, Charles, opera, simfonija, drugo
30, Adams, Brian, balada, drugo
40, Cohen,Leonard, balada, drugo
50, Donizetti, Gaetano, opera
10.	Tabeli Avtor dodajte atribut letoRojstva tipa Year. 
11.	Posodobite zapise tabele Avtor tako, da dopišete manjkajoče letnice rojstev (Orff 1895 , Gounod  1818 , Adams 1959, Cohen 1934, Donizetti 1797). Ali so se VSI podatki posodobili? Zakaj? Spremenite tip podatka letoRojstva na int in ponovno izvedite posodobitve podatkov.
12.	Izpišite vsebino tabele Avtor (stavek SELECT).
13.	Zaprite mysql.
14.	Ponovno odprite mysql in se povežite s PB GlasbenaZbirka.
15.	Ustvarite tabelo Drzava(DID:N, ImeDrzave:A20). Tabela nima primarnega ključa, tip atributa DID je auto_increment. Začetna vrednost naj bo 100. Ali je kreiranje tabele uspelo. Zakaj?
16.	Spremenite (dopolnite) prejšnji stavek DDL tako, da bo DID primarni ključ tabele.
17.	V tabelo Drzava dodajte naslednje zapise (stavek INSERT INTO):
100, Canada
200, Italia
300, Deutschland
400, France
500, Slovenija
18.	Izvedite stavek insert into drzava (imeDrzave) values ('Austria'); Katero vrednost DID je dobila Avstrija? Zakaj?
19.	Tabeli Avtor dodajte atribut DID – tuji ključ, ki kaže na tabelo država, privzeta vrednost atributa naj bo 500. 
20.	Posodobite zapise tabele Avtor tako, da dopišete manjkajoče države avtorjev. (Orff Deutschland, Gounod  France, Adams Canada, Cohen Canada, Donizetti Italia).
21.	Izpišite priimke in imena avtorjev, ki v opusu imajo opero in kantato.
22.	Iz tabele drzava izbrišite državo 300 (Deutschland). Ali je brisanje uspelo? Zakaj?
23.	Izpišite ime, priimek avtorja in ime države.
24.	Naredite izvoz PB GlasbenaZbirka_innoDB v datoteko GlasbenaZbirka_innoDB.sql.
*/

-- 1
CREATE DATABASE GlasbenaZbirka_innoDB;
-- 2
CREATE TABLE Avtor(
    AvtorID INT NOT NULL AUTO_INCREMENT, 
    Ime VARCHAR(20), 
    Priimek VARCHAR(20), 
    Opus VARCHAR(20), 
    PRIMARY KEY (AvtorID)
);

CREATE TABLE Posnetek(
    PID INT 
)